# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
  - name: Publication
    url: publication/
    weight: 40
  - name: Experience
    url: experience/
    weight: 50